# config/packages/vich_uploader.yaml or app/config/config.yml
vich_uploader:
  db_driver: orm

  metadata:
    type: attribute

  mappings:
    trick_main_image:
      uri_prefix: /images/tricks
      upload_destination: '%kernel.project_dir%/public/images/tricks'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true

    trick_image:
      uri_prefix: /images/tricks
      upload_destination: '%kernel.project_dir%/public/images/tricks'
      namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

      inject_on_load: false
      delete_on_update: true
      delete_on_remove: true